services:
  couchdb:
    image: couchdb:3.4.2 # یا couchdb:3.3.3 اگر نسخه خاصی می‌خوای
    container_name: couchdb
    restart: unless-stopped
    ports:
      - '5984:5984' # پورت وب و API
    environment:
      - COUCHDB_USER=admin # یوزر ادمین دلخواهت
      - COUCHDB_PASSWORD=secret123 # پسورد دلخواهت (حتماً عوض کن!)

# Container run command
# docker compose up -d

# Test CouchDB is running
# curl http://127.0.0.1:5984/

# Logimg to CouchDB Fauxton UI
# http://localhost:5984/_utils

